[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    # run E2E tests against the deployed URL
    record = true
    group = 'deployed'
